library("tidyverse", warn.conflicts = FALSE)
library("stringi")
library("lubridate")
library("purrr")
library("broom")
library("tidyr", warn.conflicts = FALSE)
library("ggalt")
library("kableExtra")
library("magick")
library("ggpubr")
library("plotly")
library("data.table")
library("ggrepel")
library("flexdashboard")
library("scales")
library("DT")
library("readxl")
library("readr")
theme_set(hrbrthemes::theme_ipsum())
# Suppress summarize info
options(dplyr.summarise.inform = FALSE)
